# Generated by Django 4.0.7 on 2023-07-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
