# Generated by Django 4.0.7 on 2023-07-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_application_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='last_fee_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, choices=[('appoved', 'Approved'), ('pending', 'Pending'), ('canceled', 'Canceled')], max_length=15, null=True),
        ),
    ]
